// This file is generated by Airwire
export const componentDefaults = []

import Airwire from './../../vendor/archtechx/airwire/resources/js';

export default window.Airwire = new Airwire(componentDefaults)

declare global {
    interface Window {
        Airwire: Airwire
    }
}
